### ISSUE TITLE
상징 생성시 앱 강제 종료 버그

### ISSUE THREAD

**Issue by paul2126** [snuhcs-course/swpp-2023-project-team-6#82]
카테고리하고 텍스트는 입력 되어있지만 이미지가 선택 안 된 상황에서 상징을 생성하려고 하면 아래 에러와 함께 앱이 죽습니다
```
FATAL EXCEPTION: main
Process: com.example.speechbuddy, PID: 18307
java.lang.NullPointerException
	at com.example.speechbuddy.viewmodel.SymbolCreationViewModel$createSymbol$4.invokeSuspend(SymbolCreationViewModel.kt:272)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a0ad7d4, Dispatchers.Main.immediate]
```

해당 경우 toast 띄우거나 텍스트로 이미지 선택해야한다고 알려야 할 것 같습니다

**Comment by yjeong-k** [comment]
해결하였습니다 발견해주셔서 감사합니다!!☺️
